let time_header = document.querySelector('#time-header')
let result_header = document.querySelector('#result-header')
let start = document.querySelector('start')
let game_field = document.querySelector('#game-field')
let game_time = document/querySelector('#game-time')
let time = document.querySelector('#time')
let result = document.querySelector('#result')
